### PR TITLE
missing join for knp paginator (sorting by user)

### PR DESCRIPTION
**Pull request by regisgrison**
Sorry, I forgot to include this change in the previous fix about the same bug (500 error when sorting ticjets by user).

### CODE REVIEW

**Comment by hackzilla** [comment]
Happy to merge this but I can see that this appears to have broken a test

**Comment by regisgrison** [comment]
Well... You're right but I don't understand why:

- line 202 of `TicketManager.php` is mentionned but does not refer to my change
- I just put a `innerjoin()` in the middle of the creation of an existing query
- the error is a `Call to a member function orderBy() on null` but `innerjoin()` cannot even return `null`

**Comment by hackzilla** [comment]
I've realised that the test is broken because I never mocked innerJoin.
If you add this to your PR, I can then merge it.

```diff --git a/Tests/Manager/TicketManagerTest.php b/Tests/Manager/TicketManagerTest.php
index 1604f1a..286217e 100644
--- a/Tests/Manager/TicketManagerTest.php
+++ b/Tests/Manager/TicketManagerTest.php
@@ -40,6 +40,10 @@ final class TicketManagerTest extends WebTestCase
             ->method('orderBy')
             ->willReturn($qb)
         ;
+        $qb
+            ->method('innerJoin')
+            ->willReturn($qb)
+        ;
         $qb
             ->method('andWhere')
             ->willReturn($qb)
```

**Comment by regisgrison** [comment]
Hi,

I've done what you asked.

I guess it's correct because I can see "All checks have passed".

Regards.

**Pull request merged**
